language: node_js
node_js:
  - "11"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true

before_script:
  - yarn setup
  - yarn build

after_success:
  - yarn pack

deploy:
  - provider: releases
    edge: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "pixi-yoo-ai-*.tgz"
    cleanup: true
    on:
      tags: true
  - provider: npm
    edge: true
    cleanup: true
    email: "contact@pastila.org"
    api_key: $NPM_TOKEN
    on:
      tags: true
